#ifndef PREAMBLE_GLSL
#define PREAMBLE_GLSL

#define ATTRIBUTE_LOCATION_POSITION 0
#define ATTRIBUTE_LOCATION_NORMAL 1
#define ATTRIBUTE_LOCATION_TEXCOORD 2

#define MATRICES_UNIFORM_BLOCKBINDING 0

#define TEXTURE_DIFFUSE_BINDING 0

#define RENDER_TARGET_DIFFUSE 0
#define RENDER_TARGET_POSITION 1
#define RENDER_TARGET_NORMALS 2

#endif // PREAMBLE_GLSL